name: analytics_builder
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.3.0
  source_gen: 0.9.5
  analyzer: 0.39.10
  _fe_analyzer_shared: 4.0.0
  flutter_modular: ^1.2.5+1
  analytics_annotations:
    path: ../analytics_annotations
  analytics_provider:
    path: ../analytics_provider
dev_dependencies:
  build_config: ^0.4.2
  build_runner: ^1.10.0
  freezed: ^0.10.9
  
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
